---
title: "678 final project"
author: "Yueling Feng"
date: "11/28/2022"
output: html_document
---

```{r}
## data:https://www.kaggle.com/datasets/dgomonov/new-york-city-airbnb-open-data/code?resource=download

data = read.csv("https://raw.githubusercontent.com/YueminLi/Airbnb_NYC_2019/master/AB_NYC_2019.csv",header = T)
head(data)

data=data.frame(data)
library(rstatix)
library(dbplyr)
library(ggplot2)
library(corrplot)
library(tidyverse)
library(sf)
library(mapview)
library(mapproj)
library(ggcorrplot)
## remove the price which is equal to 0 which implies the room is unavailiable
data[apply(data,1, function(x) all(data$availability_365!=0)),]
data[apply(data,1, function(x) all(data$price!=0)),]
##map view of airbnb distribution to check all the data locates at New York
mapview(data, xcol = "longitude", ycol = "latitude", crs = 4269, grid = FALSE)


```

```{r}
##remove NA values and rooms which are unavailable
data<- data %>%  na.omit()

##changing availability days in one year to availability months in one year

class(data$availability_365)

data$availability_365[data$availability_365>0&data$availability_365<=31]<-1

data$availability_365[data$availability_365>31&data$availability_365<=62]<-2

data$availability_365[data$availability_365>62&data$availability_365<=93]<-3

data$availability_365[data$availability_365>93&data$availability_365<=124]<-4

data$availability_365[data$availability_365>124&data$availability_365<=155]<-5

data$availability_365[data$availability_365>155&data$availability_365<=186]<-6

data$availability_365[data$availability_365>186&data$availability_365<=217]<-7

data$availability_365[data$availability_365>217&data$availability_365<=248]<-8

data$availability_365[data$availability_365>248&data$availability_365<=279]<-9

data$availability_365[data$availability_365>279&data$availability_365<=310]<-10

data$availability_365[data$availability_365>310&data$availability_365<=341]<-11

data$availability_365[data$availability_365>341&data$availability_365<=365]<-12

head(data)

```

```{r}
##EDA 

##remove the outliers of the prices
##reference:https://www.r-bloggers.com/2020/01/how-to-remove-outliers-in-r/

Q <- quantile(data$price, probs=c(.25, .75), na.rm = FALSE)
iqr <- IQR(warpbreaks$breaks)
data<- subset(data, data$price > (Q[1] - 1.5*iqr) & data$price < (Q[2]+1.5*iqr))

##general information about the price

mean(data$price)
min(data$price)
max(data$price)

boxplot(data$price,main="New York City 2019 Airbnb price"
                  ,ylab = "price($)")


##the correlation between price and neighbourhood_group
a=ggplot(data, aes(x = neighbourhood_group, y = price)) +
  geom_boxplot(color="red",outlier.color="black")
a+ggtitle("New York City 2019 Airbnb price compared by neighbourhood")


b=data %>%
  ggplot(aes(x = price,
             y = neighbourhood_group ,
             fill = neighbourhood_group)) +
  ggridges::geom_density_ridges(bandwidth = 4)
b+ggtitle ("New York City 2019 Airbnb price compared by neighbourhood")


data %>%
  anova_test(price ~ neighbourhood_group,
              detailed = TRUE)

kruskal.test(price ~ neighbourhood_group, data = data)
## p value < 0.05, reject the hypothesis
##reference:https://bookdown.org/daniel_dauber_io/r4np_book/comparing-groups.html


##the correlation between price and room type
a=ggplot(data, aes(x = room_type, y = price)) +
  geom_boxplot(color="red",outlier.color="black")
a+ggtitle("New York City 2019 Airbnb price compared by room_type")


b=data %>%
  ggplot(aes(x = price,
             y = room_type ,
             fill = room_type)) +
  ggridges::geom_density_ridges(bandwidth = 4)
b+ggtitle("New York City 2019 Airbnb price compared by room_type")

data %>%
  anova_test(price ~ room_type,
              detailed = TRUE)

kruskal.test(price ~ room_type, data = data)

##p value < 0.05, there is a difference in mean
##generally increase trend

##changing room type to numeric value

data$room_type[data$room_type=="Shared room"]<-1

data$room_type[data$room_type=="Private room"]<-2

data$room_type[data$room_type=="Entire home/apt"]<-3


##correlation between avaliable_month and price
fitmonth=lm(data$price~data$availability_365)
fitmonth
plot(data$price~data$availability_365, main = "month vs price"
     ,xlab = "month")
abline(fitmonth)
##there is no difference between available month and price


##correlation between min nights and price
fitminnight=lm(data$price~data$minimum_nights)
fitminnight
plot(data$price~data$minimum_nights,
     main="minimum nights vs price"
     ,xlab= "minimum nights")
abline(fitminnight)

##there is a correlation between min_nights and prices
##changing minimum night to more than 10 levels
min(data$minimum_nights)
max(data$minimum_nights)
mean(data$minimum_nights)
##at least one night

##from 2-5 days to weeks to months to years
data$minimum_nights[data$minimum_nights>1&data$minimum_nights<=5]<-2

data$minimum_nights[data$minimum_nights>5&data$minimum_nights<=7]<-3

data$minimum_nights[data$minimum_nights>7&data$minimum_nights<=14]<-4

data$minimum_nights[data$minimum_nights>14&data$minimum_nights<=21]<-5

data$minimum_nights[data$minimum_nights>21&data$minimum_nights<=28]<-6

data$minimum_nights[data$minimum_nights>28&data$minimum_nights<=35]<-7

data$minimum_nights[data$minimum_nights>35&data$minimum_nights<=60]<-8

data$minimum_nights[data$minimum_nights>60&data$minimum_nights<=90]<-9

data$minimum_nights[data$minimum_nights>90&data$minimum_nights<=120]<-10

data$minimum_nights[data$minimum_nights>120&data$minimum_nights<=200]<-11

data$minimum_nights[data$minimum_nights>200&data$minimum_nights<=360]<-12

data$minimum_nights[data$minimum_nights>360&data$minimum_nights<=720]<-13

data$minimum_nights[data$minimum_nights>720]<-14

fitminnight2=lm(data$price~data$minimum_nights)

fitminnight2

plot(data$price~data$minimum_nights,
     main="minimum nights vs price"
     ,xlab= "minimum nights")

abline(fitminnight2)



##correlation between reviews and price
fitreviews=lm(data$price~data$number_of_reviews)
fitreviews
plot(data$price~data$number_of_reviews,
     main="number of reviews vs price"
     ,xlab= "number of reviews")
abline(fitreviews)

##correlation between reviews_month and price
fitreviews=lm(data$price~data$reviews_per_month)
fitreviews
plot(data$price~data$reviews_per_month,
     main="number of reviews per month vs price"
     ,xlab= "number of reviews per month")
abline(fitreviews)
##correlation between reviews_month and minimum night
fitreviews.min=lm(data$reviews_per_month~data$minimum_nights)
fitreviews.min
plot(data$price~data$reviews_per_month,
     main="number of minimum nights vs review per month"
     ,xlab= "minimum nights")
abline(fitreviews.min)

##the correlation between review/month and neighbourhood_group
a=ggplot(data, aes(x = neighbourhood_group, y = reviews_per_month)) +
  geom_boxplot(color="red",outlier.color="black")
a+ggtitle("New York City  Airbnb review per month compared by neighbourhood")

b=data %>%
  ggplot(aes(x = reviews_per_month,
             y = neighbourhood_group ,
             fill = neighbourhood_group)) +
  ggridges::geom_density_ridges(bandwidth = 4)
b+ggtitle ("New York City Airbnb review per month compared by neighbourhood")

data %>%
  anova_test(reviews_per_month ~ neighbourhood_group,
              detailed = TRUE)
kruskal.test(reviews_per_month ~ neighbourhood_group, data = data)
## p value < 0.05, reject the hypothesis
##reference:https://bookdown.org/daniel_dauber_io/r4np_book/comparing-groups.html



##the correlation between review/month and room type
a=ggplot(data, aes(x = room_type, y = reviews_per_month)) +
  geom_boxplot(color="red",outlier.color="black")
a+ggtitle("New York City Airbnb total number of reviews compared by room_type")

b=data %>%
  ggplot(aes(x = reviews_per_month,
             y = room_type ,
             fill = room_type)) +
  ggridges::geom_density_ridges(bandwidth = 4)
b+ggtitle("New York City Airbnb total number of reviews compared by room_type")

data %>%
  anova_test(reviews_per_month ~ room_type,
              detailed = TRUE)
kruskal.test(reviews_per_month ~ room_type, data = data)

```

```{r}
##random effects


##multilevel model
library(lme4)
model=lmer(price ~ minimum_nights + reviews_per_month+ room_type + (1|minimum_nights),data=data)

summary(model)


##model checking
##reference:https://ademos.people.uic.edu/Chapter18.html
##1Linearity
plot(resid(model))

##2.Homogeneity of Variance
 
plot(model)

##3.
require("lattice")
qqmath(model, id=0.05)

##model2
library(lme4)
model2=lmer(price ~ minimum_nights + reviews_per_month+ room_type + reviews_per_month*room_type + (1|minimum_nights),data=data)

summary(model2)

##model checking

##1Linearity
plot(resid(model2))

##2.Homogeneity of Variance
 
plot(model2)

##3.
require("lattice")
qqmath(model2, id=0.05)


```




